plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
	id 'lol.bai.explosion' version "${explosion_version}"
	id 'eclipse'
}

eclipse {
	project {
		name = rootProject.name
	}
}

version = project.mod_version
group = project.maven_group

configurations {
	debugRuntime;
	sodiumRuntime;
	voxyRuntime;
	dhRuntime;

	configure([debugRuntime, sodiumRuntime, voxyRuntime, dhRuntime]) {
		exclude group: "net.fabricmc.fabric-api"
	}
}

repositories {
	maven {
		name = "badasintended/explosion"
		url = "https://maven2.bai.lol"
		content { includeGroup "lol.bai.explosion" }
	}
	maven {
		name = "DevAuth"
		url = "https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1"
	}
	maven {
		name = "Terraformers"
		url = "https://maven.terraformersmc.com/"
	}
	maven {
		name = "CaffeineMC"
		url = "https://maven.caffeinemc.net/releases"
	}
	maven {
		name = "Xander"
		url = "https://maven.isxander.dev/releases"
	}
	maven {
		name = "shedaniel"
		url = "https://maven.shedaniel.me/"
	}
	exclusiveContent {
		forRepository {
			maven {
				name = "Modrinth"
				url = "https://api.modrinth.com/maven"
			}
		}
		filter { includeGroup "maven.modrinth" }
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	modImplementation "com.terraformersmc:modmenu:${project.modmenu_version}"
	modCompileOnly "net.caffeinemc:sodium-fabric:${project.sodium_version}"

	debugRuntime "me.djtheredstoner:DevAuth-fabric:${project.devauth_version}"
	debugRuntime "maven.modrinth:remember-my-txt:${project.remember_version}"
	debugRuntime "dev.isxander:yet-another-config-lib:${project.yacl_version}"
	debugRuntime "me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}"
	debugRuntime "maven.modrinth:f5-split:${project.f5_split_version}"
	debugRuntime "maven.modrinth:freecam:${project.freecam_version}"

	sodiumRuntime "net.caffeinemc:sodium-fabric:${project.sodium_version}"
	voxyRuntime explosion.fabric("maven.modrinth:voxy:${project.voxy_version}")
	dhRuntime "maven.modrinth:distanthorizons:${project.dh_version}"
}

loom {
	runs {
		client {
			configName = "Minecraft Vanilla"
			client()
			property("fabric.addMods", "${-> configurations.debugRuntime.asPath}")
			vmArgs "-Ddevauth.enabled=true"
		}

		sodium {
			configName = "Minecraft Sodium"
			client()
			property("fabric.addMods", "${-> [
				configurations.debugRuntime.asPath,
				configurations.sodiumRuntime.asPath
			].join(File.pathSeparator)}")
			vmArgs "-Ddevauth.enabled=true"
			vmArgs "-Dmixin.debug.export=true"
		}

		voxy {
			configName = "Minecraft Voxy"
			client()
			property("fabric.addMods", "${-> [
				configurations.debugRuntime.asPath,
				configurations.sodiumRuntime.asPath,
				configurations.voxyRuntime.asPath
			].join(File.pathSeparator)}")
			vmArgs "-Ddevauth.enabled=true"
			vmArgs "-Dmixin.debug.export=true"
		}

		dh {
			configName = "Minecraft Distant Horizons"
			client()
			property("fabric.addMods", "${-> [
				configurations.debugRuntime.asPath,
				configurations.dhRuntime.asPath
			].join(File.pathSeparator)}")
			vmArgs "-Ddevauth.enabled=true"
			vmArgs "-Dmixin.debug.export=true"
		}

		remove server
	}
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

import groovy.json.JsonOutput

tasks.register('neovim') {
	group = 'ide'
	description = 'Generates Neovim launch configurations.'

	doLast {
		def runsData = loom.runs.collect { run ->
			def taskName = "run${run.name.capitalize()}"
			[
				type: "fabric-loom",
				taskName: taskName,
				name: "${run.configName} (gradlew ${taskName})",
				request: "launch",
				console: "integratedTerminal"
			]
		}
		def rootData = [
			version: "1.0.0",
			configurations: runsData
		]
		def outputFile = file(".nvim/launch.json")
		outputFile.parentFile.mkdirs()
		outputFile.text = JsonOutput.prettyPrint(JsonOutput.toJson(rootData))
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}
}
